import type { Metadata } from 'next';

import { Header } from '@/components/Header';
import { Inter } from 'next/font/google';
import { Footer } from '@/components/Footer';
import { cn } from '@/lib/utils';
import { TRPCProvider } from './_trpc/Provider';
import { MainContextProvider } from '@/contexts/MainContext';
import { serverClient } from './_trpc/serverClient';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const initialUserData = await serverClient.users.getAll();

  return (
    <html lang="en">
      <TRPCProvider>
        <MainContextProvider initialUserData={initialUserData}>
          <body className={cn(inter.className, 'min-h-screen flex flex-col')}>
            <Header />
            <main className="flex-1">{children}</main>
            <Footer />
          </body>
        </MainContextProvider>
      </TRPCProvider>
    </html>
  );
}
